### ISSUE TITLE
terraform-provider-openstack v1.32.0 binary is missing in archive v0.13 

### ISSUE THREAD

**Issue by schabrolles** [ocp-power-automation/terraform-providers-power#10] opened 2023-02-17 09:08 UTC
registry.terraform.io/terraform-provider-openstack/openstack/1.32.0/linux_ppc64le/ is created but empty

```
unzip -l archive.zip
Archive:  archive.zip
  Length      Date    Time    Name
---------  ---------- -----   ----
        0  02-01-2023 11:05   registry.terraform.io/
        0  02-01-2023 11:04   registry.terraform.io/community-terraform-providers/
        0  02-01-2023 15:32   registry.terraform.io/community-terraform-providers/ignition/
        0  02-01-2023 11:04   registry.terraform.io/community-terraform-providers/ignition/2.1.1/
        0  02-01-2023 11:09   registry.terraform.io/community-terraform-providers/ignition/2.1.1/linux_ppc64le/
 22589015  02-01-2023 11:08   registry.terraform.io/community-terraform-providers/ignition/2.1.1/linux_ppc64le/terraform-provider-ignition
        0  02-01-2023 11:04   registry.terraform.io/terraform-providers/
        0  02-01-2023 11:04   registry.terraform.io/terraform-providers/ignition/
        0  02-01-2023 11:04   registry.terraform.io/terraform-providers/ignition/1.2.1/
        0  02-01-2023 15:34   registry.terraform.io/terraform-providers/ignition/1.2.1/linux_ppc64le/
 22589095  02-01-2023 15:34   registry.terraform.io/terraform-providers/ignition/1.2.1/linux_ppc64le/terraform-provider-ignition
        0  02-01-2023 11:04   registry.terraform.io/hashicorp/
        0  02-01-2023 15:32   registry.terraform.io/hashicorp/null/
        0  02-01-2023 11:04   registry.terraform.io/hashicorp/null/2.1.2/
        0  02-01-2023 11:10   registry.terraform.io/hashicorp/null/2.1.2/linux_ppc64le/
 21004122  02-01-2023 11:10   registry.terraform.io/hashicorp/null/2.1.2/linux_ppc64le/terraform-provider-null
        0  02-01-2023 15:32   registry.terraform.io/hashicorp/random/
        0  02-01-2023 11:04   registry.terraform.io/hashicorp/random/2.3.1/
        0  02-01-2023 11:10   registry.terraform.io/hashicorp/random/2.3.1/linux_ppc64le/
 22093791  02-01-2023 11:10   registry.terraform.io/hashicorp/random/2.3.1/linux_ppc64le/terraform-provider-random
        0  02-01-2023 11:05   registry.terraform.io/terraform-provider-openstack/
        0  02-01-2023 11:05   registry.terraform.io/terraform-provider-openstack/openstack/
        0  02-01-2023 11:05   registry.terraform.io/terraform-provider-openstack/openstack/1.32.0/
        0  02-01-2023 11:05   registry.terraform.io/terraform-provider-openstack/openstack/1.32.0/linux_ppc64le/
        0  02-01-2023 11:05   registry.terraform.io/IBM-Cloud/
        0  02-01-2023 11:05   registry.terraform.io/IBM-Cloud/ibm/
        0  02-01-2023 11:05   registry.terraform.io/IBM-Cloud/ibm/1.49.0/
        0  02-01-2023 15:35   registry.terraform.io/IBM-Cloud/ibm/1.49.0/linux_ppc64le/
122166153  02-01-2023 15:35   registry.terraform.io/IBM-Cloud/ibm/1.49.0/linux_ppc64le/terraform-provider-ibm
        0  02-01-2023 15:32   registry.terraform.io/community-terraform-providers/ignition/2.1.3/
        0  02-01-2023 15:34   registry.terraform.io/community-terraform-providers/ignition/2.1.3/linux_ppc64le/
        0  02-01-2023 15:32   registry.terraform.io/hashicorp/null/3.2.1/
        0  02-01-2023 15:33   registry.terraform.io/hashicorp/null/3.2.1/linux_ppc64le/
        0  02-01-2023 15:32   registry.terraform.io/hashicorp/random/3.4.3/
        0  02-01-2023 15:33   registry.terraform.io/hashicorp/random/3.4.3/linux_ppc64le/
 25050647  02-01-2023 15:34   registry.terraform.io/community-terraform-providers/ignition/2.1.3/linux_ppc64le/terraform-provider-ignition
 21004122  02-01-2023 15:33   registry.terraform.io/hashicorp/null/3.2.1/linux_ppc64le/terraform-provider-null
 22093799  02-01-2023 15:33   registry.terraform.io/hashicorp/random/3.4.3/linux_ppc64le/terraform-provider-random
---------                     -------
278590744                     38 files
```

**Comment by yussufsh** [comment] 2023-02-24 13:44
The issue is now fixed with the latest release v0.15.
Thanks, @schabrolles for reporting this.

**Closed as completed by yussufsh** 2023-02-24 13:44 UTC
